name: CI
on:
  push:
    branches:
      - dev
      - master
  pull_request:
jobs:
  interpreter-test:
    runs-on: ${{ matrix.system }}
    strategy:
      fail-fast: false
      matrix:
        system:
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Test
        run: go test -v ./...
  build:
    needs:
      - interpreter-test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: linux
            arch: amd64
          - os: linux
            arch: arm64
          - os: darwin
            arch: amd64
          - os: darwin
            arch: arm64
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Build
        run: make GOOS=${{ matrix.platform.os }} GOARCH=${{ matrix.platform.arch }} build
      - name: Set app version
        id: app_version
        run: |
          echo "app_version=$(cat ./version.txt)" >> $GITHUB_ENV
      - name: Compose build
        run: |
          mkdir build
          cp -r ./bin ./build
          cp -r ./Lib ./build
          cp ./scripts/install.sh ./build
      - name: Upload build to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: borsch-${{ matrix.platform.os }}-${{ matrix.platform.arch }}-${{ env.app_version }}
          path: ./build
          retention-days: 60
